:PROPERTIES:
:ID:       3e748f27-e779-4a92-b63d-f107ea307b75
:END:
#+title: Contratos Inteligentes
#+date: 2023-09-06
#+filetags: :contratos:inteligentes:
- tags :: [[id:88a4cb76-7081-43d3-8b9e-58afd78624a6][Blockchain]]
- source :: [[https://www.youtube.com/watch?v=bbBbq7T9Jjs][What is a blockchain? (Video)]], [[https://www.youtube.com/watch?v=q9UzRyWRPcY][Quick Recap (Video)]], [[https://www.fon.hum.uva.nl/rob/Courses/InformationInSpeech/CDROM/Literature/LOTwinterschool2006/szabo.best.vwh.net/idea.html][The Idea of Smart Contracts]], [[https://updraft.cyfrin.io/courses/blockchain-basics/basics/smart-contract-landscape?lesson_format=transcript][Updraft Cyfrin | Current smart contract landscape]]

Contratos Inteligentes são um conjunto de instruções executadas de forma descentralizada sem precisar de terceiros ou intermediários centralizados.

Eles são similares aos contratos tradicionais, com a diferença de que são executados em plataformas blockchain.

* História
A ideia de contratos inteligentes foi concebida originalmente em 1994 por Nick Szabo.

A blockchain Ethereum a tornou realidade.

* Aplicações
- [[id:13a64c0b-7ad8-41d3-97d3-73dc9d49a5fc][Finanças Descentralizadas (DeFi)]]
- [[id:76980fce-1813-49fc-97d8-69338b224b77][Organização Descentralizada Autônoma (DAO)]]
- [[id:e7082700-d5d6-4b10-b431-d720992fac82][Token Não Fungível (NFT)]]

* Benefícios
- Descentralização
- Transparência e Flexibilidade
- Velocidade e Eficiência
- Segurança e Imutabilidade
- Eliminação de Risco de Contraparte

** Descentralização
Contratos inteligentes não dependem de nenhum intermediário centralizado.

Ao invés disso, eles dependem da blockchain, que é mantida por milhares de indivíduos conhecidos como node operators.

É esse trabalho coletivo de node operators rodando os contratos inteligentes que faz a rede ser descentralizada.

** Transparência e Flexibilidade
A transparência é herdada da blockchain.

Desde que todos os node operators possam ver o que está acontecendo na rede, não há espaço para fraudes.

Essa transparência garante que todo mundo tenha acesso às mesmas informações e jogue com as mesmas regras.

É importante que essa transparência não necessariamente quebre a privacidade.

A blockchain é pseudo-anônima. Isso significa que suas transações não são diretamente ligadas à sua identidade no mundo real.

** Velocidade e Eficiência
Contratos inteligentes e transações na blockchain são incrivelmente rápidas e eficientes comparadas ao sistema bancário tradicional.

Por exemplo: transferências bancárias, especialmente as internacionais, podem demorar várias semanas, enquanto as transações na blockchain acontecem quase instantaneamente.

** Segurança e Imutabilidade
Uma vez que um contrato inteligente é lançado (deployed),ele não pode ser alteardo e nem adulterado.

Essa imutabilidade garante que os termos do contrato sejam imutáveis.

Este é um forte contraste com sistemas centralizados onde um servidor ou banco de dados pode ser hackeado e os dados podem ser alterados.

A natureza descentralizada da blockchain faz com que hackear seja quase impossível já que o atacante terá que controlar mais da metade dos nodes da rede, o que é muito mais difícil de comprometer do que um único servidor centralizado.

Adicionalmente, os dados em uma blockchain são resilientes.

Em um sistema tradicional, se seu computador e backup falhar, você perde todos os dados.

Em contraste, na blockchain, os dados são replicados através de inúmeros nodes.

Mesmo se vários nodes caírem, os dados ainda estarão seguros com o tanto que tenha pelo menos 1 cópia da blockchain.

** Eliminação de Risco de Contraparte
Contratos inteligentes eliminam a necessidade de confiar em transações.

Uma vez que um contrato inteligente é lançado, seus termos não podem ser alterados.

Isso significa que as partes não podem alterar o acordo com base na ganância ou quaisquer outros fatores.

Isso garante que o acordo seja reforçado como pretendido originalmente.
