:PROPERTIES:
:ID:       42322fd7-bf34-4a3c-80b4-8683f517db15
:END:
#+title: Deep Learning (DL)
#+date: [2023-11-28 ter 12:39]
#+filetags: :ai:ml:nn:dl:
- tags :: [[id:a0562591-c3fe-4071-9f52-01888deeb5d0][Redes Neurais (NN)]]
- source :: [[https://learnweb3.io/degrees/ai-developer-degree/freshman-ai/introduction-to-ai/][Introduction to AI]]

DL é sigla para Aprendizado Profundo (ou Deep Learning).

Ele é um subcampo das Redes Neurais.

O termo "deep" se refere à profundidade da rede, o que significa que ela possui muitas camadas empilhadas umas sobre as outras.

No Deep Learning, as redes neurais são designadas para aprender automaticamente representações hierárquicas de dados.

Cada camada da rede processa a entrada e passa para a próxima camada, possibilitando a rede aprender cada vez mais características ou abstrações complexas conforme vai indo mais fundo na rede.

A principal vantagem do Deep Learning é a sua capacidade de descobrir e extrair automaticamente recursos relevantes de dados brutos sem a necessidade de engenharia manual de recursos. Ao invés de especificar explicitamente quais recursos procurar, os modelos de Deep Learning aprendem esses recursos dos próprios dados por meio de um processo chamado treinamento.

* Exemplos de Modelos
- [[id:c3d96626-b0ec-4ecb-9ae0-e58964b170b4][Como Funciona o GPT]]
