:PROPERTIES:
:ID:       30e86b98-d63f-400f-837b-de0ff183166c
:END:
#+title: Inteligência Artificial (AI)
#+date: [2023-11-28 ter 12:27]
#+filetags: ai
- tags ::
- source :: [[https://learnweb3.io/degrees/ai-developer-degree/freshman-ai/introduction-to-ai/][Introduction to AI]]

IA (ou AI) é uma sigla para Inteligência Artificial (ou Artificial Intelligence).

Podemos dizer, de forma básica, que criar uma Inteligência Artificial é "ensinar um computador a pensar".

Porém, computadores não pensam realmente. Nesse caso, eles apenas processam e analisam as informações de uma forma que relembra a maneira humana de pensar.

Ao invés deles seguirem regras estritas e pré-definidas, eles podem se adaptar e aprender através de diferentes exemplos e experiências.

* Exemplo
Vamos considerar, por exemplo, o reconhecimento de imagens.

Ensinar um computador a reconhecer imagens de gatos tradicionalmente envolve programar regras manuais como, por exemplo, "se a imagem contém orelhas pontudas, bigode, e uma calda, é provável que seja um gato".

Porém, com IA, podemos treinar um computador a fazer decisões mais "inteligentes". Podemos providenciar um grande conjunto de imagens com rótulos "é um gato" e "não é um gato" e o computador automaticamente aprende a reconhecer os padrões que indicam o que é um gato. Ele aprende ajustando seus parâmetros internos até que fique bom em distinguir gatos de outros objetos.

* Propósito
O propósito da IA é criar softwares que percebem, raciocinam, aprendem e fazem decisões similares aos humanos. Ela abrange uma ampla gama de técnicas, metodologias e subcampos, incluíndo Aprendizado de Máquina (ML), Processamento de Linguagem Natural (NLP), visão computacional, robótica, entre outros.

Sistemas de IA podem ser criados para tarefas específicas ou propósito geral.

* Modelos
Um modelo é como uma máquina que aprende através de exemplos. Assim como nós aprendemos algo novo vendo exemplos ou praticando, os modelos aprendem vendo muitos exemplos de informações.

** Exemplo de Modelo
Imagine que você quer construir um modelo que possa reconhecer frutas diferentes. Você começa mostrando a ele várias imagens de maçãs, laranjas, bananas, etc. O modelo olha essas imagens e aprende as características que compõem cada fruta, aprendendo, por exemplo, o que diferencia uma laranja de uma banana.

Depois de aprender através de exemplos, o modelo se torna mais inteligente. Se você mostrar a ele uma imagem nova de uma fruta, ele vai dizer qual fruta é baseado nas informações que ele aprendeu.

Quanto mais exemplos você providenciar, e quanto melhor a qualidade desses exemplos, mais inteligente ele vai se tornar. Porém, tenha em mente que modelos não são perfeitos. Às vezes, eles podem cometer erros, assim como nós quando estamos aprendendo algo novo.

** Modelos Populares
- [[id:fb364b9e-6d33-4da7-8b20-47919b35aeb5][Large Language Model (LLM)]]

* Subcampos
- [[id:4300010e-271a-418a-ac6d-c526723bf582][Aprendizado de Máquina (ML)]]
- [[id:fa6a7aa6-fe92-40d2-bf83-4844bba5b93b][Processamento de Linguagem Natural (NLP)]]
