:PROPERTIES:
:ID:       fb364b9e-6d33-4da7-8b20-47919b35aeb5
:END:
#+title: Large Language Model (LLM)
#+date: [2023-11-28 ter 12:45]
#+filetags: :ai:llm:
- tags :: [[id:30e86b98-d63f-400f-837b-de0ff183166c][Inteligência Artificial (AI)]]
- source :: [[https://learnweb3.io/degrees/ai-developer-degree/freshman-ai/intro-to-large-language-models-llms/][Intro to Large Language Models (LLMs)]]

LLM é sigla para Large Language Model (ou Modelo de Linguagem Grande).

É um tipo de modelo de Inteligência Artificial que é especializado em processar e entender a linguagem humana.

Eles são projetados para gerar texto, responder questões, e fazer outras tarefas relacionadas à linguagem.

LLMs são treinadas usando uma vasta quantidade de textos, como livros, artigos e sites. Eles aprendem os padrões, gramática e contexto da linguagem analisando essa quantidade massiva de informações.

São conhecidos por sua habilidade de entender e gerar texto parecido como nós, humanos, fazemos, podendo assim realizar tarefas como traduzir idiomas, criar resumos, fazer análise de sentimentos, gerar texto em algum idioma e muito mais.

Um dos exemplos notáveis de LLMs é a série do GPT (Generative Pre-trained Transformer) da OpenAI, que inclui modelos como o GPT-3 e o GPT-4. O Bard da Google também é um exemplo de LLM. Eles são treinados em um conjunto massivo de texto e código que incluem livros, artigos, código e outras formas de texto. Outro exemplo popular de LLM é o LLaMa da Meta.

Algo em comum entre todos esses exemplos citados é que todos eles usam Transformadores.
