:PROPERTIES:
:ID:       fa6a7aa6-fe92-40d2-bf83-4844bba5b93b
:END:
#+title: Processamento de Linguagem Natural (NLP)
#+date: [2023-11-28 ter 12:42]
#+filetags: :ai:nlp:
- tags :: [[id:30e86b98-d63f-400f-837b-de0ff183166c][Inteligência Artificial (AI)]]
- source :: [[https://learnweb3.io/degrees/ai-developer-degree/freshman-ai/introduction-to-ai/][Introduction to AI]]

PLLN (ou NLP) é uma sigla para Processamento de Linguagem Natural (ou Natural Language Processing).

É um ramo da Inteligência Artificial que foca na interação entre computadores e linguagem humana.

Ele tem aplicações significantes no mundo real como, por exemplo, melhorar motores de busca, assistentes de voz, sistemas de suporte ao consumidor, serviços de tradução de idiomas, entre outros.

Sua meta é diminuir a lacuna que existe entre a linguagem humana e as máquinas, possibilitando a comunição e interação efetiva entre humanos e máquinas.

* Propósito
O propósito da NLP é fazer com que os computadores entendam, interpretem e gerem linguagem humana.

O campo de NLP envolve desenvolver algoritmos, modelos e técnicas para processar e analisar dados de linguagem natural. Isso inclui questões e respostas, análise de sentimentos, etc.

* Tokens
Tokens são unidades ou pedaços de texto que um modelo processa durante o treinamento ou inferência. Um texto é dividido em tokens para facilitar a análise e entendimento para o modelo.

Tokens podem ser caracteres individuais, palavras, sub-palavras ou frases. A escolha específica de tokenização depende dos requisitos do modelo e da tarefa.

* Parâmetros
Parâmetros são como "configurações" (settings) ou "maçanetas" (knobs) que um modelo pode ajustar para entender melhor os dados. Eles são chamados pesos (weights) e viés (bias).

Ajustando seus valores, o modelo pode descobrir como diferenciar pedaços de informação relacionados a outros. Ele pode reconhecer padrões, correlações e relações dentro de dados.

Isso ajuda o modelo a fazer previsões precisas ou executar tarefas específicas com base na entrada fornecida.

** Pesos
Pesos (ou weights) são como forças de conexão entre diferentes partes da rede. Pense neles como "importância" ou "influência" que um pedaço de informação tem em relação a outro.

** Viés
Viés (ou bias), por outro lado, ajudam o modelo a fazer decisões. Eles agem como um "viés" em relação a certos resultados.

Se um neurônio tem um viés alto, por exemplo, é muito mais provável que ele produza um resultado.

Se um neurônio tem um viés baixo, por exemplo, é muito menos provável que ele produza um resultado.
