:PROPERTIES:
:ID:       5bcbaf54-f776-4ef7-81f4-fefa86f0d094
:END:
#+title: Transformadores (AI)
#+date: [2023-11-28 ter 12:47]
#+filetags: :ai:ml:nn:nlp:transformers:
- tags :: [[id:a0562591-c3fe-4071-9f52-01888deeb5d0][Redes Neurais (NN)]], [[id:fa6a7aa6-fe92-40d2-bf83-4844bba5b93b][Processamento de Linguagem Natural (NLP)]]
- source :: [[https://learnweb3.io/degrees/ai-developer-degree/freshman-ai/intro-to-large-language-models-llms/][Intro to Large Language Models (LLMs)]]

Transformadores são um tipo de arquitetura de Redes Neurais que revolucionou o campo de Processamento de Linguagem Natural (NLP).

Eles são projetados para processar dados sequenciais, como sentenças ou texto, capturando as relações entre as palavras ou tokens.

Diferente das redes neurais recorrentes, que processam dados de entrada de forma sequencial, os transformadores podem processar a sequência inteira em paralelo.

Isso significa que eles não precisam ler palavra por palavra. Eles podem ler a frase inteira de uma vez.

Isso os torna mais rápidos e os ajuda a entender como palavras diferentes na frase se encaixam.

Esse processamento paralelo se torna possível graças aos mecanismos que chamamos de self-attetion e attention.

Uma das principais vantagens dos transformadores é a seu longo-alcance em detectar dependências nos dados de entrada, o que é crucial para entender o contexto das palavras ou tokens em linguagem natural.

Isso os faz altamente efetivos em tarefas como tradução de linguagens, análise de sentimentos, geração de texto e muitas mais.

* Self-attention
Mecanismo que possibilita os transformadores pesarem a importância de diferentes palavras ou tokens dentro de uma frase baseado em suas relevâncias umas para as outras.

Ele calcula esses pesos considerando a relação entre todos os pares de palavras na sequência de forma simultânea.

* Attention
Esse mecanismo, por outro lado, possibilita aos transformadores focarem em partes específicas da sequência de entradas enquanto processa os dados.

Isso possibilita ao modelo atribuir maior importância para certas palavras ou tokens que são mais relevantes para a tarefa atual.
